const CONFIG = {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
  CLOUDINARY_PRESET: import.meta.env.VITE_CLOUDINARY_PRESET,
  CLOUDINARY_CLOUD_NAME: import.meta.env.VITE_CLOUDINARY_CLOUD_NAME,
};

export default CONFIG;
