export enum QUERYKEYS {
  FETCHSAMPLE = 'FETCHSAMPLE',
  FETCHINVENTORY = 'FETCHINVENTORY',
  FETCHOPERATIONS = 'FETCHOPERATIONS',
  FETCHOPERATION = 'FETCHOPERATION',

  FETCH_CUSTOMERS = 'FETCH_CUSTOMERS',
  FETCH_CUSTOMER = 'FETCH_CUSTOMER',

  FETCH_OPERATION_TYPES = 'FETCH_OPERATION_TYPES',

  FETCH_MATERIALS = 'FETCH_MATERIALS',
  FETCH_MATERIAL_TYPES = 'FETCH_MATERIAL_TYPES',
  FETCH_MATERIAL_STATE = 'FETCH_MATERIAL_STATE'
}
