export enum QUERYKEYS {
  FETCHSAMPLE = 'FETCHSAMPLE',
  FETCHINVENTORY = 'FETCHINVENTORY',
  FETCHOPERATIONS = 'FETCHOPERATIONS',
  FETCHOPERATION = 'FETCHOPERATION',

  FETCH_CUSTOMERS = 'FETCH_CUSTOMERS',
  FETCH_CUSTOMER = 'FETCH_CUSTOMER',
}
