export enum QUERYKEYS {
  FETCHSAMPLE = 'FETCHSAMPLE',

  FETCHINVENTORY = 'FETCHINVENTORY',
  FETCH_INVENTORY_BREAKDOWN = 'FETCH_INVENTORY_BREAKDOWN',

  FETCH_CUSTOMERS = 'FETCH_CUSTOMERS',
  FETCH_CUSTOMER = 'FETCH_CUSTOMER',

  FETCH_VENDORS = 'FETCH_VENDORS',
  FETCH_VENDOR = 'FETCH_VENDOR',

  FETCHOPERATION = 'FETCHOPERATION',
  FETCHOPERATIONS = 'FETCHOPERATIONS',
  FETCH_OPERATION_TYPES = 'FETCH_OPERATION_TYPES',
  FETCH_OPERATIONS_BY_BATCH = 'FETCH_OPERATIONS_BY_BATCH',
  FETCH_OPERATION_BY_ID = 'FETCH_OPERATION_BY_ID',
  FETCH_OPERATIONS_BREAKDOWN = 'FETCH_OPERATIONS_BREAKDOWN',

  FETCH_MATERIALS = 'FETCH_MATERIALS',
  FETCH_MATERIAL_TYPES = 'FETCH_MATERIAL_TYPES',
  FETCH_MATERIAL_STATE = 'FETCH_MATERIAL_STATE',

  FETCH_BANKS = 'FETCH_BANKS',

  FETCH_INVOICES = 'FETCH_INVOICES',
  FETCH_INVOICE = 'FETCH_INVOICE',

  FETCH_RECENT_ACTIVITIES = 'FETCH_RECENT_ACTIVITIES',
  FETCH_DASHBOARD_OPERATIONS = 'FETCH_DASHBOARD_OPERATIONS',
  FETCH_DASHBOARD_INVENTORY = 'FETCH_DASHBOARD_INVENTORY'
}
